name: s21_directory
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter_riverpod: ^2.3.2
  cached_network_image: ^3.2.0
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700